# This config file can be used for both run_exp.py and tune_alpha.py scripts 

deploy: True # Store run in wandb in True
exp: benchmark  # Tag is used to determine logging-directory
seed: 1996
device: cuda:1

dataset: periodic-switching
architecture: pro-transformer

# process params
process:
  t: 1000   # training horizon
  N: 20     # switching period (the task switches every N/2 times)

# train params
train:
  batch_size: 64
  lr: 0.01
  epochs: 500

# network params
net:
  aggregate_type: concat
  encoder_type: fourier
  d_model: 512
  num_heads: 8
  ff_hidden_dim: 2048
  num_attn_blocks: 1
  contextlength: 200 
  max_len: 5000
  C: 10000 # (for sinsoidal encoding)

# eval params
eval:
  T: 4000
  num_reps: 100

# Nested configs. Disable hydra logging
defaults:
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
  - override hydra/launcher: joblib

# Disable hydra directory structure
hydra:
  output_subdir: Null
  run:
    dir: .

  sweep:
    dir: .
    subdir: .

  launcher:
    n_jobs: 10